# Generated by Django 3.2.3 on 2021-05-23 16:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20210521_0752'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Smyslov')),
                ('phone', models.CharField(max_length=255, verbose_name='Phone')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('status', models.CharField(choices=[('new', 'New Order'), ('in_progress', 'Order in progress'), ('is_ready', 'Order is ready'), ('completed', 'Completed')], default='new', max_length=1024, verbose_name='Status')),
                ('buying', models.CharField(choices=[('self', 'Customer'), ('delivery', 'Delivery')], default='delivery', max_length=1024, verbose_name='Buying')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Add to database')),
                ('order_date', models.DateField(default=django.utils.timezone.now, verbose_name='Data will complete')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_orders', to='mainapp.customer', verbose_name='Customer')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='orders',
            field=models.ManyToManyField(related_name='related_customer', to='mainapp.Order', verbose_name='User orders'),
        ),
    ]
