# Generated by Django 3.2.3 on 2021-05-29 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20210528_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_key', models.CharField(max_length=150, verbose_name='Feature key')),
                ('feature_name', models.CharField(max_length=150, verbose_name='Feature name')),
                ('postfix_for_value', models.CharField(blank=True, help_text='For example, you can add "hours" for "work hours".', max_length=30, null=True, verbose_name='Value postfix')),
                ('use_in_filter', models.BooleanField(default=False, verbose_name='Use filter for products in template')),
                ('filter_type', models.CharField(choices=[('radio', 'radio'), ('checkbox', 'checkbox')], default='checkbox', max_length=30, verbose_name='Filter type')),
                ('filter_measure', models.CharField(help_text='For example, you can add "Ghz" for "processor".', max_length=50, verbose_name='Measure type')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductFeatureValidators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_value', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Characteristic type')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Category')),
                ('feature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.productfeatures', verbose_name='Feature')),
            ],
        ),
    ]
